#!/bin/sh

# Important: we manually export the used GPIO pins as doing so within openocd
# fails. The failure is caused by openocd accessing the GPIO too quickly
# after exporting, which does not give udev enough time to modify the
# permissions.
# We could run openocd as root, but that is not desireable
echo "11" > /sys/class/gpio/export
echo "12" > /sys/class/gpio/export

openocd -f orangepizero-nrf51.cfg  -f target/nrf51.cfg -c "program ../../../bin/nrf51-uart-bridge.hex reset exit"
