#pragma once

// Board definition for WaveShare BLE400 development board

#define NRF_MAXIMUM_LATENCY_US    2000


#define TIMER_COUNT                 1
#define TIMER1_ENABLED              1
#define TIMER1_CONFIG_FREQUENCY     NRF_TIMER_FREQ_1MHz
#define TIMER1_CONFIG_MODE          TIMER_MODE_MODE_Timer
#define TIMER1_CONFIG_BIT_WIDTH     TIMER_BITMODE_BITMODE_16Bit
#define TIMER1_CONFIG_IRQ_PRIORITY  APP_IRQ_PRIORITY_LOW
#define TIMER1_INSTANCE_INDEX       0


#define RTC_COUNT                   1
#define RTC0_CONFIG_FREQUENCY       100
#define RTC0_CONFIG_IRQ_PRIORITY    APP_IRQ_PRIORITY_LOW
#define RTC0_CONFIG_RELIABLE        false
#define RTC0_INSTANCE_INDEX         0

#define UART0_CONFIG_HWFC           NRF_UART_HWFC_DISABLED
#define UART0_CONFIG_PARITY         NRF_UART_PARITY_EXCLUDED
#define UART0_CONFIG_BAUDRATE       NRF_UART_BAUDRATE_115200
#define UART0_CONFIG_PSEL_TXD       9
#define UART0_CONFIG_PSEL_RXD       11
#define UART0_CONFIG_PSEL_CTS       10
#define UART0_CONFIG_PSEL_RTS       8
#define UART0_CONFIG_IRQ_PRIORITY   APP_IRQ_PRIORITY_LOW
#define UART0_CONFIG_RX_BUFFER_SIZE 128
#define UART0_CONFIG_TX_BUFFER_SIZE 128
