var CONFIG_VERSIONS = {
    1: {
        // Legend:
        // o: offset with the parent structure
        // s: element size (number of bytes)
        // c: count (number of elements)
        // h: human-friendly name (optional)
        // t: type
        //   'u': unsigned integer
        //   'i': signed integer
        //   'c': string (Note: may not be 0 terminated if it fills the element)
        //   'uuid': 64-bit (8 bytes) universally unique identifier
        //   'CONFIG': schema describes the overall config structure
        //   'TX': schema describes a transmitter
        //   'MODEL': schema describes a model
        //   any other value: refers to named elements in TYPES[]

        CONFIG: { t: 'CONFIG', o: 0, s: 4476, c: 1,
            VERSION: {o: 0, s: 4, c: 1, t: 'u'},
            TX: {o: 4, s: 1588, c: 1, t: 's'},
            MODEL: {o: 1592, s: 2884, c: 1, t: 's'},
        },

        TX: { o: 4, s: 1588, c: 1, t: 'TX',
            UUID: {t: 'uuid', o: 0, s: 1, c: 8},
            NAME: {t: 'c', o: 8, s: 1, c: 16},
            LAST_CHANGED: {t: 'u', o: 24, s: 4, c: 1},
            TAG: {t: 'u', o: 28, s: 4, c: 1},
            HARDWARE_INPUTS: {t: 's', o: 32, s: 28, c: 32},
            HARDWARE_INPUTS_PCB_INPUT: {t: 's', o: 32, s: 20, c: 1},
            HARDWARE_INPUTS_PCB_INPUT_GPIOPORT: {t: 'u', o: 32, s: 4, c: 1},
            HARDWARE_INPUTS_PCB_INPUT_GPIO: {t: 'u', o: 36, s: 2, c: 1},
            HARDWARE_INPUTS_PCB_INPUT_ADC_CHANNEL: {t: 'u', o: 38, s: 1, c: 1},
            HARDWARE_INPUTS_PCB_INPUT_TYPE: {t: 'pcb_input_type_t', o: 39, s: 1, c: 1},
            HARDWARE_INPUTS_PCB_INPUT_PIN_NAME: {t: 'c', o: 40, s: 1, c: 10},
            HARDWARE_INPUTS_TYPE: {t: 'hardware_input_type_t', o: 52, s: 1, c: 1},
            HARDWARE_INPUTS_CALIBRATION: {t: 'u', o: 54, s: 2, c: 3},
            LOGICAL_INPUTS: {t: 's', o: 928, s: 20, c: 32},
            LOGICAL_INPUTS_TYPE: {t: 'input_type_t', h: 'Input type', o: 928, s: 1, c: 1},
            LOGICAL_INPUTS_SUB_TYPE: {t: 'input_sub_type_t', h: 'Push-button behavior', o: 929, s: 1, c: 1},
            LOGICAL_INPUTS_POSITION_COUNT: {t: 'u', o: 930, s: 1, c: 1},
            LOGICAL_INPUTS_HARDWARE_INPUTS: {t: 'u', h: 'Hardware inputs', o: 931, s: 1, c: 12},
            LOGICAL_INPUTS_LABELS: {t: 'input_label_t', h: 'Input labels', o: 943, s: 1, c: 5},
            TRIM_RANGE: {t: 'i', o: 1568, s: 4, c: 1},
            TRIM_STEP_SIZE: {t: 'i', o: 1572, s: 4, c: 1},
            BIND_TIMEOUT_MS: {t: 'u', o: 1576, s: 4, c: 1},
            DOUBLE_CLICK_TIMEOUT_MS: {t: 'u', o: 1580, s: 4, c: 1},
            PASSPHRASE: {t: 'u', o: 1584, s: 2, c: 1},
            LED_PWM_PERCENT: {t: 'u', o: 1586, s: 1, c: 1},
            METER_PWM_PERCENT: {t: 'u', o: 1587, s: 1, c: 1},
        },

        MODEL: { o: 1592, s: 2884, c: 1, t: 'MODEL',
            UUID: {t: 'uuid', o: 0, s: 1, c: 8},
            NAME: {t: 'c', o: 8, s: 1, c: 16},
            LAST_CHANGED: {t: 'u', o: 24, s: 4, c: 1},
            TAG: {t: 'u', o: 28, s: 4, c: 1},
            MIXER_UNITS: {t: 's', o: 32, s: 26, c: 100},
            MIXER_UNITS_CURVE: {t: 's', o: 32, s: 15, c: 1},
            MIXER_UNITS_CURVE_TYPE: {t: 'curve_type_t', o: 32, s: 1, c: 1},
            MIXER_UNITS_CURVE_SMOOTHING: {t: 'interpolation_type_t', o: 33, s: 1, c: 1},
            MIXER_UNITS_CURVE_POINTS: {t: 'i', o: 34, s: 1, c: 13},
            MIXER_UNITS_SRC: {t: 'src_label_t', h: 'Source', o: 47, s: 1, c: 1},
            MIXER_UNITS_DST: {t: 'channel_label_t', h: 'Destination', o: 48, s: 1, c: 1},
            MIXER_UNITS_SW: {t: 's', o: 49, s: 3, c: 1},
            MIXER_UNITS_SW_SW: {t: 'switch_label_t', h: 'Switch', o: 49, s: 1, c: 1},
            MIXER_UNITS_SW_CMP: {t: 'comparison_t', h: 'Comparison', o: 50, s: 1, c: 1},
            MIXER_UNITS_SW_VALUE: {t: 'u', o: 51, s: 1, c: 1},
            MIXER_UNITS_OP: {t: 'operation_type_t', h: 'Operation', o: 52, s: 1, c: 1},
            MIXER_UNITS_SCALAR: {t: 'i', o: 53, s: 1, c: 1},
            MIXER_UNITS_OFFSET: {t: 'i', o: 54, s: 1, c: 1},
            MIXER_UNITS_TAG: {t: 'u', o: 57, s: 1, c: 1},
            MIXER_UNITS_INVERT_SOURCE: {t: 'u', o: 55, s: 1, c: 1},
            MIXER_UNITS_APPLY_TRIM: {t: 'u', o: 56, s: 1, c: 1},
            LIMITS: {t: 's', o: 2632, s: 28, c: 8},
            LIMITS_EP_L: {t: 'i', o: 2632, s: 4, c: 1},
            LIMITS_EP_H: {t: 'i', o: 2636, s: 4, c: 1},
            LIMITS_SUBTRIM: {t: 'i', o: 2640, s: 4, c: 1},
            LIMITS_LIMIT_L: {t: 'i', o: 2644, s: 4, c: 1},
            LIMITS_LIMIT_H: {t: 'i', o: 2648, s: 4, c: 1},
            LIMITS_FAILSAFE: {t: 'i', o: 2652, s: 4, c: 1},
            LIMITS_SPEED: {t: 'u', o: 2656, s: 1, c: 1},
            LIMITS_INVERT: {t: 'u', o: 2657, s: 1, c: 1},
            RF_PROTOCOL_TYPE: {t: 'rf_protocol_type_t', o: 2856, s: 1, c: 1},
            RF: {t: 's', o: 2857, s: 25, c: 1},
            RF_PROTOCOL_HK310: {t: 's', o: 2857, s: 25, c: 1},
            RF_PROTOCOL_HK310_HOP_CHANNELS: {t: 'u', o: 2857, s: 1, c: 20},
            RF_PROTOCOL_HK310_ADDRESS: {t: 'u', o: 2877, s: 1, c: 5},
        },

        TYPES: {
            pcb_input_type_t: {
                'Analog/Digital': 1,
                'Digital': 2,
            },
            hardware_input_type_t: {
                'Input not used': 0,
                'Analog, returns to center': 1,
                'Analog, center detent': 2,
                'Analog': 3,
                'Analog, positive only': 4,
                'On/Off switch': 5,
                'On/Off/On switch': 6,
                'Push-button': 7,
            },
            hardware_input_type_t_digital: {
                'Input not used': 0,
                'On/Off switch': 5,
                'On/Off/On switch': 6,
                'Push-button': 7,
            },
            input_type_t: {
                'Analog': 1,
                'Switch': 2,
                'BCD switch': 3,
                'Momentary switch': 4,
                'Trim': 5,
            },
            input_sub_type_t: {
                'Up/Down buttons': 1,
                'Increment-and-loop': 2,
                'Decrement-and-loop': 3,
                'Sawtooth': 4,
                'Double-click for decrement': 5,
            },
            input_label_t: {
                'ST': 1,
                'TH': 2,
                'THR': 3,
                'RUD': 4,
                'AIL': 5,
                'ELE': 6,
                'AUX': 7,
                'ST-DR': 8,
                'RUD-DR': 9,
                'AIL-DR': 10,
                'ELE-DR': 11,
                'TH-DR': 12,
                'THR-DR': 13,
                'TH-HOLD': 14,
                'GEAR': 15,
                'FLAPS': 16,
                'TRAINER': 17,
                'SIDE-L': 18,
                'SIDE-R': 19,
                'POT1': 20,
                'POT2': 21,
                'POT3': 22,
                'POT4': 23,
                'POT5': 24,
                'POT6': 25,
                'POT7': 26,
                'POT8': 27,
                'POT9': 28,
                'SW1': 29,
                'SW2': 30,
                'SW3': 31,
                'SW4': 32,
                'SW5': 33,
                'SW7': 35,
                'SW8': 36,
                'SW9': 37,
            },
            switch_label_t: {
                'NONE': 0,
                'ST': 1,
                'TH': 2,
                'THR': 3,
                'RUD': 4,
                'AIL': 5,
                'ELE': 6,
                'AUX': 7,
                'ST-DR': 8,
                'RUD-DR': 9,
                'AIL-DR': 10,
                'ELE-DR': 11,
                'TH-DR': 12,
                'THR-DR': 13,
                'TH-HOLD': 14,
                'GEAR': 15,
                'FLAPS': 16,
                'TRAINER': 17,
                'SIDE-L': 18,
                'SIDE-R': 19,
                'POT1': 20,
                'POT2': 21,
                'POT3': 22,
                'POT4': 23,
                'POT5': 24,
                'POT6': 25,
                'POT7': 26,
                'POT8': 27,
                'POT9': 28,
                'SW1': 29,
                'SW2': 30,
                'SW3': 31,
                'SW4': 32,
                'SW5': 33,
                'SW7': 35,
                'SW8': 36,
                'SW9': 37,
            },
            channel_label_t: {
                'CH1': 0,
                'CH2': 1,
                'CH3': 2,
                'CH4': 3,
                'CH5': 4,
                'CH6': 5,
                'CH7': 6,
                'CH8': 7,
                'VIRTUAL1': 8,
                'VIRTUAL2': 9,
                'VIRTUAL3': 10,
                'VIRTUAL4': 11,
                'VIRTUAL5': 12,
                'VIRTUAL6': 13,
                'VIRTUAL7': 14,
                'VIRTUAL8': 15,
                'VIRTUAL9': 16,
                'VIRTUAL10': 17,
            },
            src_label_t: {
                'ST': 2,
                'TH': 3,
                'THR': 4,
                'RUD': 5,
                'AIL': 6,
                'ELE': 7,
                'AUX': 8,
                'ST-DR': 9,
                'RUD-DR': 10,
                'AIL-DR': 11,
                'ELE-DR': 12,
                'TH-DR': 13,
                'THR-DR': 14,
                'TH-HOLD': 15,
                'GEAR': 16,
                'FLAPS': 17,
                'TRAINER': 18,
                'SIDE-L': 19,
                'SIDE-R': 20,
                'POT1': 21,
                'POT2': 22,
                'POT3': 23,
                'POT4': 24,
                'POT5': 25,
                'POT6': 26,
                'POT7': 27,
                'POT8': 28,
                'POT9': 29,
                'SW1': 30,
                'SW2': 31,
                'SW3': 32,
                'SW4': 33,
                'SW5': 34,
                'SW7': 36,
                'SW8': 37,
                'SW9': 38,
                'CH1': 39,
                'CH2': 40,
                'CH3': 41,
                'CH4': 42,
                'CH5': 43,
                'CH6': 44,
                'CH7': 45,
                'CH8': 46,
                'VIRTUAL1': 47,
                'VIRTUAL2': 48,
                'VIRTUAL3': 49,
                'VIRTUAL4': 50,
                'VIRTUAL5': 51,
                'VIRTUAL6': 52,
                'VIRTUAL7': 53,
                'VIRTUAL8': 54,
                'VIRTUAL9': 55,
                'VIRTUAL10': 56,
            },
            live_t: {
                'ST': 1,
                'TH': 2,
                'THR': 3,
                'RUD': 4,
                'AIL': 5,
                'ELE': 6,
                'AUX': 7,
                'ST-DR': 8,
                'RUD-DR': 9,
                'AIL-DR': 10,
                'ELE-DR': 11,
                'TH-DR': 12,
                'THR-DR': 13,
                'TH-HOLD': 14,
                'GEAR': 15,
                'FLAPS': 16,
                'TRAINER': 17,
                'SIDE-L': 18,
                'SIDE-R': 19,
                'POT1': 20,
                'POT2': 21,
                'POT3': 22,
                'POT4': 23,
                'POT5': 24,
                'POT6': 25,
                'POT7': 26,
                'POT8': 27,
                'POT9': 28,
                'SW1': 29,
                'SW2': 30,
                'SW3': 31,
                'SW4': 32,
                'SW5': 33,
                'SW7': 35,
                'SW8': 36,
                'SW9': 37,
                'CH1': 38,
                'CH2': 39,
                'CH3': 40,
                'CH4': 41,
                'CH5': 42,
                'CH6': 43,
                'CH7': 44,
                'CH8': 45,
                'VIRTUAL1': 46,
                'VIRTUAL2': 47,
                'VIRTUAL3': 48,
                'VIRTUAL4': 49,
                'VIRTUAL5': 50,
                'VIRTUAL6': 51,
                'VIRTUAL7': 52,
                'VIRTUAL8': 53,
                'VIRTUAL9': 54,
                'VIRTUAL10': 55,
                'HIDDEN1': 56,
                'HIDDEN2': 57,
                'HIDDEN3': 58,
                'HIDDEN4': 59,
                'HIDDEN5': 60,
                'HIDDEN6': 61,
                'HIDDEN7': 62,
                'HIDDEN8': 63,
                'HIDDEN9': 64,
                'HIDDEN10': 65,
                'HIDDEN11': 66,
                'HIDDEN12': 67,
                'HIDDEN13': 68,
                'HIDDEN14': 69,
                'HIDDEN15': 70,
                'HIDDEN16': 71,
                'HIDDEN17': 72,
                'HIDDEN18': 73,
                'HIDDEN19': 74,
                'HIDDEN20': 75,
                'HIDDEN21': 76,
                'HIDDEN22': 77,
                'HIDDEN23': 78,
                'HIDDEN24': 79,
                'HIDDEN25': 80,
                'HIDDEN26': 81,
                'HIDDEN27': 82,
                'HIDDEN28': 83,
                'HIDDEN29': 84,
                'HIDDEN30': 85,
                'HIDDEN31': 86,
                'HIDDEN32': 87,
                'HIDDEN33': 88,
                'HIDDEN34': 89,
                'HIDDEN35': 90,
                'HIDDEN36': 91,
                'HIDDEN37': 92,
                'HIDDEN38': 93,
                'HIDDEN39': 94,
                'HIDDEN40': 95,
                'HIDDEN41': 96,
                'HIDDEN42': 97,
                'HIDDEN43': 98,
                'HIDDEN44': 99,
                'HIDDEN45': 100,
                'HIDDEN46': 101,
                'HIDDEN47': 102,
                'HIDDEN48': 103,
                'HIDDEN49': 104,
                'HIDDEN50': 105,
                'RF-CH1': 106,
                'RF-CH2': 107,
                'RF-CH3': 108,
                'RF-CH4': 109,
                'RF-CH5': 110,
                'RF-CH6': 111,
                'RF-CH7': 112,
                'RF-CH8': 113,
                'Battery (mV)': 114,
                'ADC0 (raw)': 115,
                'ADC1 (raw)': 116,
                'ADC2 (raw)': 117,
                'ADC3 (raw)': 118,
                'ADC4 (raw)': 119,
                'ADC5 (raw)': 120,
                'ADC6 (raw)': 121,
                'ADC7 (raw)': 122,
                'ADC8 (raw)': 123,
                'ADC9 (raw)': 124,
                'ADC10 (raw)': 125,
                'ADC11 (raw)': 126,
                'ADC12 (raw)': 127,
                'ADC13 (raw)': 128,
                'ADC14 (raw)': 129,
                'ADC15 (raw)': 130,
                'ADC16 (raw)': 131,
                'ADC17 (raw)': 132,
                'ADC18 (raw)': 133,
                'ADC19 (raw)': 134,
                'ADC20 (raw)': 135,
                'ADC21 (raw)': 136,
                'ADC22 (raw)': 137,
                'ADC23 (raw)': 138,
                'ADC24 (raw)': 139,
                'ADC25 (raw)': 140,
                'ADC26 (raw)': 141,
                'ADC27 (raw)': 142,
                'ADC28 (raw)': 143,
                'ADC29 (raw)': 144,
                'ADC30 (raw)': 145,
                'ADC31 (raw)': 146,
            },
            rf_protocol_type_t: {
                'HobbyKing HKR3000': 0,
                'RF_PROTOCOL_LANEBOYSRC4CH': 1,
            },
            operation_type_t: {
                '=': 0,
                '+': 1,
                '*': 2,
                'MIN': 3,
                'MAX': 4,
            },
            comparison_t: {
                '==': 0,
                '!=': 1,
                '>': 2,
                '>=': 3,
                '<': 4,
                '<=': 5,
            },
            curve_type_t: {
                'Linear': 0,
                'Fixed value': 1,
                'Min/Max': 2,
                '0/Max': 3,
                '>0': 4,
                '<0': 5,
                'Absolute': 6,
                'Expo': 7,
                'Deadband': 8,
                '3-Point': 9,
                '5-Point': 10,
                '7-Point': 11,
                '9-Point': 12,
                '11-Point': 13,
                '13-Point': 14,
            },
            interpolation_type_t: {
                'Linear': 0,
                'Smoothing': 1,
            },
            curve_points_t: {
                "Linear": [],
                "Fixed value": ["Value"],
                "Min/Max": ["Threshold"],
                "0/Max": ["Threshold"],
                ">0": ["Threshold"],
                "<0": ["Threshold"],
                "Absolute": ["Threshold"],
                "Expo": [">0", "<0"],
                "Deadband": [">0", "<0"],
                "3-Point": ["-100%", "0", "+100%"],
                "5-Point": ["-100%", "-50%", "0", "+50%", "+100%"],
                "7-Point": ["-100%", "-66%", "-33%", "0", "+33%", "+66%", "+100%"],
                "9-Point": ["-100%", "-75%", "-50%", "-25%", "0", "+25", "+50%", "+75%", "+100%"],
                "11-Point": ["-100%", "-80%", "-60%", "-40%", "-20%", "0", "+20%", "+40%", "+60%", "+80%", "+100%"],
                "13-Point": ["-100%", "-83%", "-67%", "-50%", "-33%", "-17%", "0", "+17%", "+33%", "+50%", "+67%", "+83%", "+100%"],
            },
        }
    }
};

window['CONFIG_VERSIONS'] = CONFIG_VERSIONS;
